## Тема “Вычисления с помощью Numpy” 
# Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [3]:
a0 = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a0

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [4]:
a = a0.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

# Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [7]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [34]:
N = a_centered.shape[0]
N

5

In [35]:
c_t = a_centered.T
c_t

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [36]:
c = c_t.flatten()
c

array([-1. ,  0. ,  1. ,  1. , -1. , -2.4, -0.4,  2.6,  1.6, -1.4])

In [37]:
c1 = c[:N]
c1

array([-1.,  0.,  1.,  1., -1.])

In [38]:
c2 = c[N: ]
c2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [39]:
a_centered_sp = c1 @ c2
a_centered_sp

8.0

Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [40]:
a_centered_sp_div = a_centered_sp / (N - 1)
a_centered_sp_div

2.0

In [18]:
c = np.split(a_centered, 2, axis = 1)
c

[array([[-1.],
        [ 0.],
        [ 1.],
        [ 1.],
        [-1.]]),
 array([[-2.4],
        [-0.4],
        [ 2.6],
        [ 1.6],
        [-1.4]])]

In [ ]:
a_centered_sp = 